### ISSUE TITLE
Entrega Trabajo Práctico N° 1

### ISSUE THREAD

**Issue by franmoli** [TomasR264/2020_K2001_Grupo_7#1]
Solicito corrección del trabajo práctico @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

El trabajo está muy bien pero faltan algunas cosas

1) El enunciado pide que deben generar un archivo de salida, llamado "salida.txt". Por lo que veo ustedes imprimen por pantalla pero no generan un archivo de salida.
2) Las columnas de a-f , y A-F mayúscula pueden ir juntas.

Pero lo más importante es que resuelvan el punto 1)

Saludos,

Santiago
