### ISSUE TITLE
Solicito correccion de TP Nro 4

### ISSUE THREAD

**Issue by TomasR264** [TomasR264/2020_K2001_Grupo_7#4]
Entrega de TP4, esperamos la correccion de errores : @santiagoferreiros  (Mil disculpas por la demora)

**Comment by santiagoferreiros** [comment]
Estimado grupo,

Estuve viendo el trabajo. Considero que es mejor reunirnos la próxima semana y que me cuenten un poco donde están teniendo inconvenientes. Veo una gramática bastante amplia, pero a la hora de ejecutar no está derivando correctamente.
Lo ideal es que utilicen el modo debug para podes rastrear lo que está sucediendo. 

Por el momento continúo con el resto de las entregas (son más de 20). Una vez que finalice, la próxima semana podemos coordinar un horario para reunirnos fuera de clase.

Saludos,

Santiago
